/**
 * Global design constants — colors, fonts, and shared static values.
 * Centralised here so any brand update touches one file.
 */

/** Brand colour palette matching theme.css tokens */
export const COLORS = {
  gold: '#C9A96E',
  goldDark: '#A8833F',
  navy: '#1A2744',
  navyLight: '#243659',
  navyDeep: '#0F1A2E',
  ivory: '#FAF8F5',
  ivoryWarm: '#FAF6F0',
  border: 'rgba(26,39,68,0.09)',
} as const;

/** Inline serif font — used where Tailwind font utilities don't apply (e.g. style prop) */
export const FONT_SERIF = "'Playfair Display', serif";

/** Unsplash hero background image — sized down + compressed for faster LCP on mobile */
export const HERO_IMAGE_URL =
  'https://images.unsplash.com/photo-1523374228107-6e44bd2b524e?w=1200&h=675&fit=crop&auto=format&q=60';

/** Investment property types available for multi-select in the consultation form */
export const PROPERTY_TYPES = ['Commercial', 'Residential', 'Plots', 'Luxury'] as const;

/** Budget range options for the consultation form dropdown */
export const BUDGET_OPTIONS = [
  'Under ₹50 Lakhs',
  '₹50L – ₹1 Crore',
  '₹1 Crore – ₹3 Crore',
  '₹3 Crore – ₹10 Crore',
  '₹10 Crore+',
] as const;


export const COUNTRY_CODES = [
  // ── Most relevant (India + top Indian-diaspora markets) ──
  { name: 'India', dialCode: '+91', flag: '🇮🇳' },
  { name: 'United States', dialCode: '+1', flag: '🇺🇸' },
  { name: 'United Kingdom', dialCode: '+44', flag: '🇬🇧' },
  { name: 'UAE', dialCode: '+971', flag: '🇦🇪' },
  { name: 'Saudi Arabia', dialCode: '+966', flag: '🇸🇦' },
  { name: 'Canada', dialCode: '+1', flag: '🇨🇦' },
  { name: 'Australia', dialCode: '+61', flag: '🇦🇺' },
  { name: 'Singapore', dialCode: '+65', flag: '🇸🇬' },

  // ── Rest of the world (A–Z) ──
  { name: 'Afghanistan', dialCode: '+93', flag: '🇦🇫' },
  { name: 'Albania', dialCode: '+355', flag: '🇦🇱' },
  { name: 'Algeria', dialCode: '+213', flag: '🇩🇿' },
  { name: 'Argentina', dialCode: '+54', flag: '🇦🇷' },
  { name: 'Armenia', dialCode: '+374', flag: '🇦🇲' },
  { name: 'Austria', dialCode: '+43', flag: '🇦🇹' },
  { name: 'Azerbaijan', dialCode: '+994', flag: '🇦🇿' },
  { name: 'Bahrain', dialCode: '+973', flag: '🇧🇭' },
  { name: 'Bangladesh', dialCode: '+880', flag: '🇧🇩' },
  { name: 'Belarus', dialCode: '+375', flag: '🇧🇾' },
  { name: 'Belgium', dialCode: '+32', flag: '🇧🇪' },
  { name: 'Bhutan', dialCode: '+975', flag: '🇧🇹' },
  { name: 'Bolivia', dialCode: '+591', flag: '🇧🇴' },
  { name: 'Bosnia and Herzegovina', dialCode: '+387', flag: '🇧🇦' },
  { name: 'Brazil', dialCode: '+55', flag: '🇧🇷' },
  { name: 'Brunei', dialCode: '+673', flag: '🇧🇳' },
  { name: 'Bulgaria', dialCode: '+359', flag: '🇧🇬' },
  { name: 'Cambodia', dialCode: '+855', flag: '🇰🇭' },
  { name: 'Chile', dialCode: '+56', flag: '🇨🇱' },
  { name: 'China', dialCode: '+86', flag: '🇨🇳' },
  { name: 'Colombia', dialCode: '+57', flag: '🇨🇴' },
  { name: 'Costa Rica', dialCode: '+506', flag: '🇨🇷' },
  { name: 'Croatia', dialCode: '+385', flag: '🇭🇷' },
  { name: 'Cyprus', dialCode: '+357', flag: '🇨🇾' },
  { name: 'Czech Republic', dialCode: '+420', flag: '🇨🇿' },
  { name: 'Denmark', dialCode: '+45', flag: '🇩🇰' },
  { name: 'Ecuador', dialCode: '+593', flag: '🇪🇨' },
  { name: 'Egypt', dialCode: '+20', flag: '🇪🇬' },
  { name: 'Estonia', dialCode: '+372', flag: '🇪🇪' },
  { name: 'Ethiopia', dialCode: '+251', flag: '🇪🇹' },
  { name: 'Fiji', dialCode: '+679', flag: '🇫🇯' },
  { name: 'Finland', dialCode: '+358', flag: '🇫🇮' },
  { name: 'France', dialCode: '+33', flag: '🇫🇷' },
  { name: 'Georgia', dialCode: '+995', flag: '🇬🇪' },
  { name: 'Germany', dialCode: '+49', flag: '🇩🇪' },
  { name: 'Ghana', dialCode: '+233', flag: '🇬🇭' },
  { name: 'Greece', dialCode: '+30', flag: '🇬🇷' },
  { name: 'Guatemala', dialCode: '+502', flag: '🇬🇹' },
  { name: 'Hong Kong', dialCode: '+852', flag: '🇭🇰' },
  { name: 'Hungary', dialCode: '+36', flag: '🇭🇺' },
  { name: 'Iceland', dialCode: '+354', flag: '🇮🇸' },
  { name: 'Indonesia', dialCode: '+62', flag: '🇮🇩' },
  { name: 'Iran', dialCode: '+98', flag: '🇮🇷' },
  { name: 'Iraq', dialCode: '+964', flag: '🇮🇶' },
  { name: 'Ireland', dialCode: '+353', flag: '🇮🇪' },
  { name: 'Israel', dialCode: '+972', flag: '🇮🇱' },
  { name: 'Italy', dialCode: '+39', flag: '🇮🇹' },
  { name: 'Jamaica', dialCode: '+1876', flag: '🇯🇲' },
  { name: 'Japan', dialCode: '+81', flag: '🇯🇵' },
  { name: 'Jordan', dialCode: '+962', flag: '🇯🇴' },
  { name: 'Kazakhstan', dialCode: '+7', flag: '🇰🇿' },
  { name: 'Kenya', dialCode: '+254', flag: '🇰🇪' },
  { name: 'Kuwait', dialCode: '+965', flag: '🇰🇼' },
  { name: 'Latvia', dialCode: '+371', flag: '🇱🇻' },
  { name: 'Lebanon', dialCode: '+961', flag: '🇱🇧' },
  { name: 'Libya', dialCode: '+218', flag: '🇱🇾' },
  { name: 'Lithuania', dialCode: '+370', flag: '🇱🇹' },
  { name: 'Luxembourg', dialCode: '+352', flag: '🇱🇺' },
  { name: 'Malaysia', dialCode: '+60', flag: '🇲🇾' },
  { name: 'Maldives', dialCode: '+960', flag: '🇲🇻' },
  { name: 'Malta', dialCode: '+356', flag: '🇲🇹' },
  { name: 'Mauritius', dialCode: '+230', flag: '🇲🇺' },
  { name: 'Mexico', dialCode: '+52', flag: '🇲🇽' },
  { name: 'Monaco', dialCode: '+377', flag: '🇲🇨' },
  { name: 'Mongolia', dialCode: '+976', flag: '🇲🇳' },
  { name: 'Morocco', dialCode: '+212', flag: '🇲🇦' },
  { name: 'Myanmar', dialCode: '+95', flag: '🇲🇲' },
  { name: 'Nepal', dialCode: '+977', flag: '🇳🇵' },
  { name: 'Netherlands', dialCode: '+31', flag: '🇳🇱' },
  { name: 'New Zealand', dialCode: '+64', flag: '🇳🇿' },
  { name: 'Nigeria', dialCode: '+234', flag: '🇳🇬' },
  { name: 'North Korea', dialCode: '+850', flag: '🇰🇵' },
  { name: 'Norway', dialCode: '+47', flag: '🇳🇴' },
  { name: 'Oman', dialCode: '+968', flag: '🇴🇲' },
  { name: 'Pakistan', dialCode: '+92', flag: '🇵🇰' },
  { name: 'Panama', dialCode: '+507', flag: '🇵🇦' },
  { name: 'Papua New Guinea', dialCode: '+675', flag: '🇵🇬' },
  { name: 'Paraguay', dialCode: '+595', flag: '🇵🇾' },
  { name: 'Peru', dialCode: '+51', flag: '🇵🇪' },
  { name: 'Philippines', dialCode: '+63', flag: '🇵🇭' },
  { name: 'Poland', dialCode: '+48', flag: '🇵🇱' },
  { name: 'Portugal', dialCode: '+351', flag: '🇵🇹' },
  { name: 'Qatar', dialCode: '+974', flag: '🇶🇦' },
  { name: 'Romania', dialCode: '+40', flag: '🇷🇴' },
  { name: 'Russia', dialCode: '+7', flag: '🇷🇺' },
  { name: 'Rwanda', dialCode: '+250', flag: '🇷🇼' },
  { name: 'Serbia', dialCode: '+381', flag: '🇷🇸' },
  { name: 'Seychelles', dialCode: '+248', flag: '🇸🇨' },
  { name: 'Slovakia', dialCode: '+421', flag: '🇸🇰' },
  { name: 'Slovenia', dialCode: '+386', flag: '🇸🇮' },
  { name: 'South Africa', dialCode: '+27', flag: '🇿🇦' },
  { name: 'South Korea', dialCode: '+82', flag: '🇰🇷' },
  { name: 'Spain', dialCode: '+34', flag: '🇪🇸' },
  { name: 'Sri Lanka', dialCode: '+94', flag: '🇱🇰' },
  { name: 'Sudan', dialCode: '+249', flag: '🇸🇩' },
  { name: 'Sweden', dialCode: '+46', flag: '🇸🇪' },
  { name: 'Switzerland', dialCode: '+41', flag: '🇨🇭' },
  { name: 'Syria', dialCode: '+963', flag: '🇸🇾' },
  { name: 'Taiwan', dialCode: '+886', flag: '🇹🇼' },
  { name: 'Tanzania', dialCode: '+255', flag: '🇹🇿' },
  { name: 'Thailand', dialCode: '+66', flag: '🇹🇭' },
  { name: 'Trinidad and Tobago', dialCode: '+1868', flag: '🇹🇹' },
  { name: 'Tunisia', dialCode: '+216', flag: '🇹🇳' },
  { name: 'Turkey', dialCode: '+90', flag: '🇹🇷' },
  { name: 'Uganda', dialCode: '+256', flag: '🇺🇬' },
  { name: 'Ukraine', dialCode: '+380', flag: '🇺🇦' },
  { name: 'Uruguay', dialCode: '+598', flag: '🇺🇾' },
  { name: 'Uzbekistan', dialCode: '+998', flag: '🇺🇿' },
  { name: 'Venezuela', dialCode: '+58', flag: '🇻🇪' },
  { name: 'Vietnam', dialCode: '+84', flag: '🇻🇳' },
  { name: 'Yemen', dialCode: '+967', flag: '🇾🇪' },
  { name: 'Zambia', dialCode: '+260', flag: '🇿🇲' },
  { name: 'Zimbabwe', dialCode: '+263', flag: '🇿🇼' },
] as const;